FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc \
    postgresql-client \
    libpq-dev \
    poppler-utils \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir uv debugpy

COPY pyproject.toml ./

RUN uv pip install --system -r pyproject.toml

COPY . .

RUN mkdir -p /app/logs /app/data/uploads



EXPOSE 8000 5678 5679


CMD ["python", "-m", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]