"""add_response_metadata_to_messages

Revision ID: 46ccfbe1b629
Revises: 45f7c8dbd22b
Create Date: 2026-02-13 15:37:28.482837

"""
from alembic import op
import sqlalchemy as sa


revision = '46ccfbe1b629'
down_revision = '45f7c8dbd22b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('response_cached', sa.Boolean(), nullable=True))
    op.add_column('messages', sa.Column('response_type', sa.String(length=50), nullable=True))
    op.add_column('messages', sa.Column('response_metadata', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'response_metadata')
    op.drop_column('messages', 'response_type')
    op.drop_column('messages', 'response_cached')
    # ### end Alembic commands ###
